---
name: Casnic
version: "1.37.0"
slug: casnic
description: Casnic Controller
url: https://github.com/bitsii/addons-casnic/tree/main
#ingress: true
#ingress_port: 3200
auth_api: true
webui: http://[HOST]:[PORT:3200]
init: false
"services": [
    "mqtt:need"
]
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  3200/tcp: 3200
ports_description:
  3200/tcp: Used for web interface
hassio_api: true

